# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1/vivado-essentials/fifo_8x2048/fifo_8x2048.xci
# IP: The module: 'fifo_8x2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1/vivado-essentials/fifo_8x2048/fifo_8x2048/fifo_8x2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8x2048'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1/vivado-essentials/fifo_8x2048/fifo_8x2048.xci
# IP: The module: 'fifo_8x2048' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1/vivado-essentials/fifo_8x2048/fifo_8x2048/fifo_8x2048.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_8x2048'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
