# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/xillydemo.xdc

# Block Designs: D:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/vivado_system/vivado_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system || ORIG_REF_NAME==vivado_system}]

# IP: D:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/vivado_system/ip/vivado_system_xillybus_lite_0_0/vivado_system_xillybus_lite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_xillybus_lite_0_0 || ORIG_REF_NAME==vivado_system_xillybus_lite_0_0}]

# IP: D:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/vivado_system/ip/vivado_system_xillybus_ip_0_0/vivado_system_xillybus_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_xillybus_ip_0_0 || ORIG_REF_NAME==vivado_system_xillybus_ip_0_0}]

# IP: D:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/vivado_system/ip/vivado_system_xillyvga_0_0/vivado_system_xillyvga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_xillyvga_0_0 || ORIG_REF_NAME==vivado_system_xillyvga_0_0}]

# IP: D:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_0/vivado_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_processing_system7_0_0 || ORIG_REF_NAME==vivado_system_processing_system7_0_0}]

# IP: D:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==vivado_system_rst_processing_system7_0_100M_0}]

# IP: D:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/vivado_system/ip/vivado_system_xlconcat_0_0/vivado_system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_xlconcat_0_0 || ORIG_REF_NAME==vivado_system_xlconcat_0_0}]

# IP: D:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_axi_periph_0/vivado_system_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==vivado_system_processing_system7_0_axi_periph_0}]

# IP: D:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/vivado_system/ip/vivado_system_xbar_0/vivado_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_xbar_0 || ORIG_REF_NAME==vivado_system_xbar_0}]

# IP: D:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_0/vivado_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_auto_pc_0 || ORIG_REF_NAME==vivado_system_auto_pc_0}]

# XDC: d:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_0/vivado_system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==vivado_system_processing_system7_0_0 || ORIG_REF_NAME==vivado_system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: d:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==vivado_system_rst_processing_system7_0_100M_0}]

# XDC: d:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vivado_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==vivado_system_rst_processing_system7_0_100M_0}]

# XDC: d:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: d:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/vivado_system/ip/vivado_system_xbar_0/vivado_system_xbar_0_ooc.xdc

# XDC: d:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_0/vivado_system_auto_pc_0_ooc.xdc

# XDC: D:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1.3-tested-fifo-and-da-vhdl-ad/vivado-essentials/vivado_system/vivado_system_ooc.xdc
