# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1/vivado-essentials/vga_fifo/vga_fifo.xci
# IP: The module: 'vga_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1/vivado-essentials/vga_fifo/vga_fifo/vga_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1/vivado-essentials/vga_fifo/vga_fifo/vga_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1/vivado-essentials/vga_fifo/vga_fifo.xci
# IP: The module: 'vga_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1/vivado-essentials/vga_fifo/vga_fifo/vga_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/Courex/FPGA/ProJ/xilinux/DAQ_sys_v_1/vivado-essentials/vga_fifo/vga_fifo/vga_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'vga_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
